apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-group16
  labels: 
    app: group16-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: group16-app
  template:
    metadata:
      labels:
        app: group16-app
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8080",
          "--service=api-group16.endpoints.grupo16.cloud.goog",
          "--rollout_strategy=managed",
        ]
        ports:
          - containerPort: 8081
      - name: group16-app
        image: gcr.io/grupo16/imageclassification
        ports:
        - containerPort: 8080