apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-group16
  labels: 
    app: group16-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: group16-app
  template:
    metadata:
      labels:
        app: group16-app
    spec:
      containers:
      - name: group16-app
        image: gcr.io/grupo16/imageclassification
        ports:
        - containerPort: 8080
    
