apiVersion: v1
kind: Service
metadata: 
  name: group16-service
  labels: 
    app: group16-app
spec:
  type: LoadBalancer
  selector:
    app: group16-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080