apiVersion: v1
kind: Service
metadata: 
  name: group16-service
  labels: 
    app: group16-app
spec:
  type: LoadBalancer
  selector:
    app: group16-app-service1
    app: group16-app-service2
    app: group16-app-service3
    app: group16-app-service4
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 180
